# Generated by Django 4.2 on 2023-07-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About_me",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="To'liq ism:")),
                ("job", models.CharField(max_length=50, verbose_name="Kasbi")),
                ("body", models.TextField(verbose_name="Men haqimda:")),
                ("degree", models.CharField(max_length=100, verbose_name="Darajas:")),
                (
                    "phone_number",
                    models.CharField(max_length=9, verbose_name="Telefon nomer:"),
                ),
                ("address", models.CharField(max_length=300, verbose_name="Manzil:")),
                (
                    "birthday",
                    models.CharField(
                        help_text="ushbu ko'rinishda kiriting: 01.12.2024",
                        max_length=20,
                        verbose_name="Tug'ilgan sana:",
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        help_text="Yil kiriting", max_length=2, verbose_name="Tajriba"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, verbose_name="Elektron pochta:"),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                ("image", models.ImageField(upload_to="my_image")),
                (
                    "social_telegram",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="Telegram:"
                    ),
                ),
                (
                    "social_linkedin",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="LinkedIn:"
                    ),
                ),
                (
                    "social_youtube",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="You Tube:"
                    ),
                ),
                (
                    "social_instagram",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="Instagram:"
                    ),
                ),
                (
                    "social_facebook",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="Facebook:"
                    ),
                ),
                (
                    "github",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="Git Hub:"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expericence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job", models.CharField(max_length=200, verbose_name="Kasbi")),
                (
                    "working",
                    models.CharField(max_length=200, verbose_name="Ishlagan joyi"),
                ),
                (
                    "date",
                    models.CharField(
                        help_text="shu ko'rinishda kiriting: 2024-2030",
                        max_length=9,
                        verbose_name="Ishlagan vaqti",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Ishda nimalar qilgansiz va qanday natijalarga erishgansiz",
                        verbose_name="Qilgan ishim",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("image", models.ImageField(upload_to="portfolio-images")),
                ("link", models.TextField()),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("body", models.CharField(max_length=500)),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Skill nomi")),
                (
                    "degree",
                    models.CharField(
                        max_length=3, verbose_name="Skillning bilish darajasi"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("body", models.CharField(max_length=150)),
                ("job", models.CharField(max_length=50, verbose_name="Kasbi:")),
                (
                    "image",
                    models.ImageField(
                        default="client-images/default.jpg", upload_to="client-images"
                    ),
                ),
            ],
        ),
    ]
